

module AbsE where

-- Haskell module generated by the BNF converter




newtype PIdent = PIdent ((Int,Int),String)
  deriving (Eq, Ord, Show, Read)
data Program = PDefs [Decl] | PTDefs [AnnotatedDecl]
  deriving (Eq, Ord, Show, Read)

data AnnotatedDecl = UntypedDecl Decl | ADecl Type Decl
  deriving (Eq, Ord, Show, Read)

data Decl = DeclFun LExpr [Arg] Guard CompStmt | DeclStmt Stmt
  deriving (Eq, Ord, Show, Read)

data Arg = ArgDecl Modality PIdent Guard
  deriving (Eq, Ord, Show, Read)

data Modality = ModEmpty | ModVar | ModDef
  deriving (Eq, Ord, Show, Read)

data Guard = GuardVoid | GuardType Type
  deriving (Eq, Ord, Show, Read)

data Stmt
    = StmtExpr Expr
    | StmtDeclV LExpr Guard
    | StmtVIterDeclV LExpr Guard
    | StmtEIterDeclV Expr LExpr Guard
    | StmtVarInitV LExpr Guard Expr
    | StmtDeclD LExpr Guard
    | StmtVIterDeclD LExpr Guard
    | StmtEIterDeclD Expr LExpr Guard
    | StmtVarInitD LExpr Guard Expr
    | StmtIterInit LExpr Guard TypeIter
    | StmtReturn Expr
    | StmtNoReturn
    | SComp CompStmt
    | StmtIfElse Expr CompStmt Stmt
    | StmtIfNoElse Expr CompStmt
    | SSwitchCase Expr [NormCase] [DfltCase]
    | StmtBreak
    | StmtContinue
    | StmtWhile Expr CompStmt
    | StmtFor PIdent TypeIter CompStmt
  deriving (Eq, Ord, Show, Read)

data CompStmt = StmtBlock [Decl]
  deriving (Eq, Ord, Show, Read)

data NormCase = CaseNormal Expr CompStmt
  deriving (Eq, Ord, Show, Read)

data DfltCase = CaseDefault CompStmt
  deriving (Eq, Ord, Show, Read)

data Expr
    = StmtAssign LExpr AssignOperator Expr
    | LeftExpr LExpr
    | ExprInt Integer
    | ExprDouble Double
    | ExprChar Char
    | ExprString String
    | ExprTrue
    | ExprFalse
    | ExprFunCall PIdent [Expr]
    | ExprBoolNot Expr
    | ExprRef LExpr
    | ExprDeref LExpr
    | ExprNegation Expr
    | ExprAddition Expr
    | ExprPower Expr Expr
    | ExprMul Expr Expr
    | ExprFloatDiv Expr Expr
    | ExprIntDiv Expr Expr
    | ExprReminder Expr Expr
    | ExprModulo Expr Expr
    | ExprPlus Expr Expr
    | ExprMinus Expr Expr
    | ExprIntInc Expr Expr
    | ExprIntExc Expr Expr
    | ExprLt Expr Expr
    | ExprGt Expr Expr
    | ExprLtEq Expr Expr
    | ExprGtEq Expr Expr
    | ExprEq Expr Expr
    | ExprNeq Expr Expr
    | ExprAnd Expr Expr
    | ExprOr Expr Expr
  deriving (Eq, Ord, Show, Read)

data LExpr = LExprArray LExpr Expr | LExprId PIdent
  deriving (Eq, Ord, Show, Read)

data AssignOperator
    = OpAssign
    | OpOr
    | OpAnd
    | OpPlus
    | OpMinus
    | OpMul
    | OpIntDiv
    | OpFloatDiv
    | OpRemainder
    | OpModulo
    | OpPower
  deriving (Eq, Ord, Show, Read)

data Type
    = TypeBool
    | TypeDouble
    | TypeInt
    | TypeVoid
    | TypeChar
    | TypeString
    | TypeCompound CompoundType
  deriving (Eq, Ord, Show, Read)

data CompoundType = TypePointer Type | TypeIterable TypeIter
  deriving (Eq, Ord, Show, Read)

data TypeIter = TypeIterInterval Expr | TypeIterArray [Expr]
  deriving (Eq, Ord, Show, Read)

