{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintETAC where

-- pretty-printer generated by Enrico che vuole solo andare a dormire

import PrintE
import AbsETAC
import Data.Char

instance Print TACProgram where
  prt i e = case e of
    _ -> prPrec i 0 (concatD [prt 0 e])
    --TAC inst -> prPrec i 0 (concatD [prt 0 inst])

{-
instance Print TAC where
    prt i e = case e of
        AssignIntTemp temp@(name,pos,type_) val -> prPrec i 0 (concatD [prt 0 name, doc (showString "@"), prt 0 pos, doc (showString "="), prt 0 type_, prt 0 val])
    -}